version: '3.8'

services:
  db:
    image: postgres:12.3-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      .env

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/static/
      - media_value:/media/
    depends_on:
      - backend

volumes:
  postgres_data:
  static_value:
  media_value: